package ar.edu.um.temira.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SleepDetectorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSleepDetectorAllPropertiesEquals(SleepDetector expected, SleepDetector actual) {
        assertSleepDetectorAutoGeneratedPropertiesEquals(expected, actual);
        assertSleepDetectorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSleepDetectorAllUpdatablePropertiesEquals(SleepDetector expected, SleepDetector actual) {
        assertSleepDetectorUpdatableFieldsEquals(expected, actual);
        assertSleepDetectorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSleepDetectorAutoGeneratedPropertiesEquals(SleepDetector expected, SleepDetector actual) {
        assertThat(expected)
            .as("Verify SleepDetector auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSleepDetectorUpdatableFieldsEquals(SleepDetector expected, SleepDetector actual) {
        assertThat(expected)
            .as("Verify SleepDetector relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSleepDetectorUpdatableRelationshipsEquals(SleepDetector expected, SleepDetector actual) {
        // empty method
    }
}
