package ar.edu.um.temira.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VehicleBrandAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleBrandAllPropertiesEquals(VehicleBrand expected, VehicleBrand actual) {
        assertVehicleBrandAutoGeneratedPropertiesEquals(expected, actual);
        assertVehicleBrandAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleBrandAllUpdatablePropertiesEquals(VehicleBrand expected, VehicleBrand actual) {
        assertVehicleBrandUpdatableFieldsEquals(expected, actual);
        assertVehicleBrandUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleBrandAutoGeneratedPropertiesEquals(VehicleBrand expected, VehicleBrand actual) {
        assertThat(expected)
            .as("Verify VehicleBrand auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleBrandUpdatableFieldsEquals(VehicleBrand expected, VehicleBrand actual) {
        assertThat(expected)
            .as("Verify VehicleBrand relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleBrandUpdatableRelationshipsEquals(VehicleBrand expected, VehicleBrand actual) {
        // empty method
    }
}
